# 🚚 Supply Chain & Inventory Performance Intelligence Executive Report

**Project Title:** Enterprise Supply Chain Analytics & ABC/XYZ Inventory Strategy Model  
**Domain:** Global Supply Chain & Logistics Analytics  
**Tech Stack:** PostgreSQL (Star Schema), Python (EDA & Matrix Segmentation), Power BI Desktop (DAX Modeling)  

---

## 1. Executive Summary

This end-to-end supply chain analytics solution evaluates operational bottlenecks, carrier lead-time variances, and inventory holding risks using the **DataCo Global Supply Chain Dataset**. By establishing a **PostgreSQL Star Schema**, running **Python ABC/XYZ inventory matrix calculations**, and building an **Interactive Power BI Executive Dashboard**, this project provides actionable strategies to improve fulfillment performance and optimize inventory working capital.

---

## 2. Key Business Metrics & Performance Snapshot

* **Gross Sales Revenue:** **$36.78M** total revenue processed across global logistics channels[cite: 3].
* **Overall Late Delivery Rate:** **54.83%** of all orders experienced delivery delays beyond scheduled delivery windows[cite: 3].
* **OTIF Rate (On-Time In-Full):** **17.84%** fulfillment efficiency across regional hubs[cite: 3].
* **Core Revenue Concentration:** **$28.28M (76.8% of total revenue)** is generated by just **7 high-performing SKUs**[cite: 1, 3].

---

## 3. In-Depth Analytical Insights & Key Findings

### A. Carrier Bottlenecks & Lead-Time Variance
* **First Class Carrier SLA Failure:** First Class shipping suffers from an extreme **95.32% delay rate**, making it the least reliable delivery channel despite premium pricing[cite: 3].
* **Second Class Delay Rate:** Second Class shipments experience a **76.88% delay rate**[cite: 3].
* **Same Day Shipping:** Shows a **48.74% delay rate**[cite: 3].
* **Standard Class Performance:** Standard Class is the most reliable option with the lowest delay rate of **38.07%**[cite: 3].

### B. ABC / XYZ Inventory Matrix Analysis

By pairing **Revenue Pareto Segmentation (ABC)**[cite: 1] with **Demand Volatility Coefficient of Variation (XYZ)**[cite: 1], products are mapped into 9 distinct matrix groups:

| Segment | Revenue & Volatility Profile | SKU Count | Total Revenue Impact | Recommended Safety Stock Policy |
| :---: | :--- | :---: | :---: | :--- |
| **AX** | High Revenue, Stable Demand[cite: 1] | **7** | **$28.28M (76.8%)** | **Tight Automated Control:** Continuous review with minimal buffer stock[cite: 1]. |
| **BX** | Medium Revenue, Stable Demand[cite: 1] | **2** | **$4.16M (11.3%)** | **Standard Reordering:** Fixed reorder points with periodic audits[cite: 1]. |
| **BY / BZ** | Medium Revenue, Variable/Volatile Demand[cite: 1] | **14** | **$2.50M (6.8%)** | **Dynamic Buffer Stock:** Safety stock re-evaluated monthly[cite: 1]. |
| **CY / CZ** | Low Revenue, Variable/Volatile Demand[cite: 1] | **95** | **$1.86M (5.1%)** | **On-Demand / Drop-ship:** Minimal stocking; low priority reordering[cite: 1]. |

* **AX High Value Protection:** Protection of the 7 **AX** items is critical to safeguarding 76.8% of total business revenue[cite: 1, 3].
* **Long-Tail Capital Working Risk:** **53 SKUs** sit in the **CZ** class[cite: 1] (low revenue, high volatility[cite: 1]), tying up warehouse space and working capital.

---

## 4. Strategic Recommendations & Action Plan

1. **Carrier Contract Renegotiation:** Re-evaluate carrier SLAs for First Class express routing to lower the 95.32% delay rate[cite: 3].
2. **Automated ERP Reordering:** Implement automated reorder triggers for the top 7 **AX** SKUs to protect $28.28M in core revenue[cite: 1].
3. **Inventory Rationalization:** Shift the 53 **CZ** items to a Drop-Shipping or Vendor-Managed Inventory (VMI) model to optimize working capital[cite: 1].
